#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from src.freelance_leads_bot.integrations.config import IntegrationSettings
from src.freelance_leads_bot.integrations.expert_rag import ExpertRagStore
from src.freelance_leads_bot.integrations.service_catalog import ServiceCatalogStore


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Seed service catalog and migrate Expert RAG service_key metadata.")
    sub = parser.add_subparsers(dest="command", required=True)
    sub.add_parser("seed", help="Create default service catalog items if missing.")
    plan = sub.add_parser("migration-plan", help="Print dry-run migration plan for Expert RAG service_key metadata.")
    plan.add_argument("--status", default="approved")
    plan.add_argument("--limit", type=int, default=1000)
    apply = sub.add_parser("migration-apply", help="Apply a migration plan JSON generated by migration-plan.")
    apply.add_argument("--plan", required=True, type=Path)
    args = parser.parse_args(argv)

    settings = IntegrationSettings.from_env()
    catalog = ServiceCatalogStore(settings.rag_service_catalog_path)
    store = ExpertRagStore(settings.rag_expert_db_path)

    if args.command == "seed":
        items = catalog.seed_defaults()
        print(json.dumps({"created": [item.to_dict() for item in items], "count": len(items)}, ensure_ascii=False, indent=2))
        return 0
    if args.command == "migration-plan":
        catalog.seed_defaults()
        rows = catalog.plan_expert_rag_service_key_migration(store, status=args.status, limit=args.limit)
        print(json.dumps({"items": rows, "count": len(rows)}, ensure_ascii=False, indent=2))
        return 0
    if args.command == "migration-apply":
        payload = json.loads(args.plan.read_text(encoding="utf-8"))
        rows = payload.get("items") if isinstance(payload, dict) else payload
        updated = catalog.apply_expert_rag_service_key_migration(store, rows if isinstance(rows, list) else [])
        print(json.dumps({"updated_ids": updated, "count": len(updated)}, ensure_ascii=False, indent=2))
        return 0
    return 2


if __name__ == "__main__":
    raise SystemExit(main())
